// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxugolxepjddbayccfnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4dWdvbHhlcGpkZGJheWNjZm5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0Mzc3MzksImV4cCI6MjA2MzAxMzczOX0.cZzW1G6d6nbhzB8lkwrwrOwllXLubOSTxtfWxHlWHJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);